export const CONFIG = {
  jsxStyledExt: '.styled.tsx',
  cssStyledExt: '.styled.ts',
  componentExt: '.component.tsx',
  sliceExt: '.slice.ts',
  i18Ext: '.i18n.ts',
  typeExt: '.type.ts',
  componentPathAlias: '&components/',
  featurePathAlias: '&features/',
  styledPathAlias: '&styled/',
  featureDefaultPath: '../app/features/',
  reusableComponentsDefaultPath: '../app/styled/',
  withComments: true,
  i18nPath: '../app/locales/',
  i18nLangs: ['ar', 'en'],
  i18nToken: '[TOKEN]:LOCALS',
  reducersToken: '[TOKEN]:REDUCERS',
  reducersImportToken: '[TOKEN]:IMPORTS_REDUCERS',
  reduxRootReducerPath: '../app/store/',
  reduxRootReducerFileName: 'rootReducer.ts',
};
